version: '3'
services:
  schlundddns:
    image: customelements/schlund-ddns
    container_name: schlund-ddns
    ports:
      - "5000:5000"
    volumes:
      - ./.schlund-ddns:/schlund-ddns/.schlund-ddns
    environment:
      - DDNS_CONFIG=/schlund-ddns/.schlund-ddns
